export {
  authAPI,
  dashboardAPI,
  customerAPI,
  leadAPI,
  followUpAPI,
  ticketAPI,
  technicianAPI,
  installationAPI,
  testingAPI,
  dailyProgressLogAPI,
  inventoryAPI,
  warehouseAPI,
  amcAPI,
  maintenanceTicketAPI,
  serviceVisitAPI,
  warrantyAPI,
  warrantyClaimAPI,
  vendorEscalationAPI,
  siteSurveyAPI,
  solarDesignAPI,
  quotationAPI,
  projectApprovalAPI,
  projectProgressAPI,
  purchaseOrderAPI,
  commissioningAPI,
  attendanceAPI,
  taskAssignmentAPI,
  teamScheduleAPI,
  technicianLocationAPI,
  dailyReportAPI,
  technicianTaskAPI,
  receiptAPI,
  creditNoteAPI,
  invoiceAPI,
  vendorPaymentAPI,
  subsidyAPI,
  reportAPI,  documentAPI,
  documentCategoryAPI,
  productCategoryAPI,
  productAPI,
  vendorAPI,
  notificationAPI,
  fileUrl,
} from "./api";
 